[manifest]

id = "mm_recomp_bomb_arrows"

version = "1.0.1"

display_name = "Bomb Arrows"

description = """
Adds the ability to combine arrows with bombs like in other Zelda titles. \
Fasten a bomb to the tip of an arrow, causing it to detonate on impact or when the fuse expires.

To use bomb arrows, assign both the Hero's Bow and Bombs to the same control button. \
Each bomb arrow consumes one arrow and one bomb."""

short_description = "Combine arrows with bombs for explosive projectiles."

authors = ["PK Cheap"]

game_id = "mm"

minimum_recomp_version = "1.2.2"

dependencies = ["mm_recomp_interface_helper:1.1.0"]

optional_dependencies = ["mm_recomp_arrow_cycling"]

native_libraries = []

[inputs]

elf_path = "build/mod.elf"

mod_filename = "mm_recomp_bomb_arrows"

func_reference_syms_file = "Zelda64RecompSyms/mm.us.rev1.syms.toml"
data_reference_syms_files = [
	"Zelda64RecompSyms/mm.us.rev1.datasyms.toml",
	"Zelda64RecompSyms/mm.us.rev1.datasyms_static.toml",
]

additional_files = ["thumb.dds"]
